/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function containsConfusable(input: string): boolean
export function isConfusableWith(input: string, other: string): boolean
export function confusableContains(input: string, other: string): boolean
export function replaceConfusable(input: string): string
export function detectReplaceConfusable(input: string): string
