/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Checks whether the string contains any confusable characters. */
export function containsConfusable(input: string): boolean
/** Checks whether the current string is confusable with another string. */
export function isConfusableWith(input: string, other: string): boolean
/** A `str.includes` method that is resilient to confusables. */
export function confusableContains(input: string, other: string): boolean
/** Replaces all confusable characters. */
export function replaceConfusable(input: string): string
/**
 * Replaces all confusables characters, if any.
 *
 * It first checks whether the input contains any confusable
 * characters in the first place. If you are certain it does,
 * you can call `replace_confusable` directly,
 * otherwise this might save you an allocation.
 */
export function detectReplaceConfusable(input: string): string
